Bug 541264 - java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
Fix target platform to include javax.xml.bind bundle from Orbit due to
Java 11 removing this module.
Adjust bundles to import javax.xml.bind* bundles.

Signed-off-by: Alexander Kurtakov <akurtako@redhat.com>